import type { Dayjs } from "dayjs";

// ================================
// ENUM ДЛЯ КЛАССИФИКАЦИИ
// ================================

export enum Difficulty {
  EASY = "easy",
  MEDIUM = "medium",
  HARD = "hard",
}

export enum MealType {
  BREAKFAST = "breakfast",
  LUNCH = "lunch",
  DINNER = "dinner",
  SNACK = "snack",
  DESSERT = "dessert",
}

export enum Category {
  BREAKFAST = "breakfast",
  LUNCH = "lunch",
  DINNER = "dinner",
  DESSERT = "dessert",
  APPETIZER = "appetizer",
  SALAD = "salad",
  MAIN_COURSE = "main_course",
  SOUP = "soup",
  BAKING = "baking",
  DRINK = "drink",
  SAUCE = "sauce",
  SIDE_DISH = "side_dish",
}

export enum DayOfWeek {
  MONDAY = "monday",
  TUESDAY = "tuesday",
  WEDNESDAY = "wednesday",
  THURSDAY = "thursday",
  FRIDAY = "friday",
  SATURDAY = "saturday",
  SUNDAY = "sunday",
}

export enum Unit {
  // Weight
  GRAMS = "g",
  KILOGRAMS = "kg",
  MILLIGRAMS = "mg",

  // Volume
  MILLILITERS = "ml",
  LITERS = "l",
  TEASPOON = "tsp",
  TABLESPOON = "tbsp",
  CUP = "cup",

  // Count
  PIECES = "pcs",
  BUNCH = "bunch",
  CLOVE = "clove",
  STALK = "stalk",

  // Other
  PINCH = "pinch",
  TO_TASTE = "to_taste",
  SERVING = "serving",
  PACKAGE = "package",
}

// ================================
// ОСНОВНЫЕ ИНТЕРФЕЙСЫ ДАННЫХ
// ================================

export interface IIngredient {
  id: string;
  name: string;
  amount: number;
  unit: Unit;
  note?: string;
  category?: string;
}

export interface ICookingStep {
  id: string;
  order: number;
  description: string;
  duration?: number;
  imageUrl?: string;
  timerEnabled?: boolean;
}

export interface INutritionInfo {
  calories?: number;
  protein?: number;
  carbs?: number;
  fat?: number;
  fiber?: number;
  sugar?: number;
}

export interface IRecipe {
  id: string;
  title: string;
  description: string;
  imageUrl?: string;
  servings: number;
  prepTime: number;
  cookTime: number;
  difficulty: Difficulty;
  category: Category;
  tags: string[];

  ingredients: IIngredient[];
  steps: ICookingStep[];

  notes?: string;
  source?: string;
  nutrition?: INutritionInfo;

  createdAt: Dayjs;
  updatedAt: Dayjs;
  favorite: boolean;
  rating?: number;
}

// ================================
// ПЛАНИРОВАНИЕ И РАСПИСАНИЕ
// ================================

export interface IScheduledRecipe {
  id: string;
  recipeId: string;
  date: Dayjs;
  dayOfWeek: DayOfWeek;
  mealType: MealType;
  servings: number;
  completed: boolean;
}

export interface IMealPlanMeal {
  id: string;
  mealType: MealType;
  recipeId?: string;
  customMeal?: string;
  scheduledRecipeId?: string;
}

export interface IMealPlanDay {
  date: Dayjs;
  dayOfWeek: DayOfWeek;
  meals: IMealPlanMeal[];
}

export interface IMealPlan {
  id: string;
  weekStart: Dayjs;
  days: IMealPlanDay[];
}

// ================================
// СПИСОК ПОКУПОК
// ================================

export interface IShoppingListItem {
  id: string;
  ingredientName: string;
  originalName: string;
  amount: number;
  unit: Unit;
  purchased: boolean;
  category: string;
  recipes: string[];
  note?: string;
  autoGenerated: boolean;
}

export interface IShoppingList {
  id: string;
  name: string;
  items: IShoppingListItem[];
  createdAt: Dayjs;
  completed: boolean;
}

// ================================
// РЕЖИМ ПРИГОТОВЛЕНИЯ
// ================================

export interface ICookingSession {
  id: string;
  recipeId: string;
  currentStepIndex: number;
  isActive: boolean;
  startTime?: Dayjs;
  completedStepIds: string[];
  timerEnd?: Dayjs;
  paused: boolean;
  totalTime: number;
}
